#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TapGame.Resource", IsApplication=true)]

namespace TapGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microcharts.Droid.Resource.String.library_name = global::TapGame.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int light_blue_500 = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ScoreItemBackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int TapBlue = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int acceptChangesButton = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int fragmentContainer = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int helloTextView = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int mainLayout = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int nameTextView = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int placeTextView = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int playerNameEditText = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int plotView = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int scoreTextView = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int scoresListView = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int settingsButton = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int showGraphButton = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int showResultsButton = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int startGameButton = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int tvCounter = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int tvTap = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int tvTime = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Graph = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ScoreItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Scores = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Settings = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
